let countryList = [
   {"id": 1,
   "name": "Afghanistan",
   "iso3": "AFG",
   "iso2": "AF",
   "numeric_code": "004",
   "phone_code": "93",
   "capital": "Kabul",},
   { "id": 2,
   "name": "Aland Islands",
   "iso3": "ALA",
   "iso2": "AX",
   "numeric_code": "248",
   "phone_code": "+358-18",
   "capital": "Mariehamn",},
   {"id": 3,
   "name": "Albania",
   "iso3": "ALB",
   "iso2": "AL",
   "numeric_code": "008",
   "phone_code": "355",
   "capital": "Tirana",},
   { "id": 4,
   "name": "Algeria",
   "iso3": "DZA",
   "iso2": "DZ",
   "numeric_code": "012",
   "phone_code": "213",
   "capital": "Algiers",},
   {"id": 5,
   "name": "American Samoa",
   "iso3": "ASM",
   "iso2": "AS",
   "numeric_code": "016",
   "phone_code": "+1-684",
   "capital": "Pago Pago",},
   { "id": 6,
   "name": "Andorra",
   "iso3": "AND",
   "iso2": "AD",
   "numeric_code": "020",
   "phone_code": "376",
   "capital": "Andorra la Vella",},
   {"id": 7,
   "name": "Angola",
   "iso3": "AGO",
   "iso2": "AO",
   "numeric_code": "024",
   "phone_code": "244",
   "capital": "Luanda",},
   {"id": 8,
   "name": "Anguilla",
   "iso3": "AIA",
   "iso2": "AI",
   "numeric_code": "660",
   "phone_code": "+1-264",
   "capital": "The Valley",},
   { "id": 9,
   "name": "Antarctica",
   "iso3": "ATA",
   "iso2": "AQ",
   "numeric_code": "010",
   "phone_code": "672",
   "capital": "",},
   {"id": 10,
   "name": "Antigua And Barbuda",
   "iso3": "ATG",
   "iso2": "AG",
   "numeric_code": "028",
   "phone_code": "+1-268",
   "capital": "St. John's",},
]
export{countryList};